version: "3.9"

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"   # Port exposat al runner
    environment:
      - NODE_ENV=development

  backend:
    build: ./servidor
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=server.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
