version: "3.9"

services:
  backend:
    build: ./servidor
    container_name: backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "80:80"
    restart: unless-stopped

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    depends_on:
      - frontend
    environment:
      NGROK_AUTHTOKEN: "${NGROK_AUTHTOKEN}"
      NGROK_PORT: "frontend:80"
    ports:
      - "4040:4040"
